### ISSUE TITLE
How calculate publication cost for SCOAP3 publication?

### ISSUE THREAD

**Issue by UlfKronman** [Kungbib/openapc-se#6]
Enter calculation instructions for SCOAP publications, if this is considered to be a valid calculation:
I teorin skulle man väl kunna säga att APC:n/kostnaden för en SCOAP-publikation är organisationens avgift till SCOAP delat med antalet publikationer som organisationens forskare publicerat i SCOAP-tidskrifter under året.

**Comment by camillalindelow** [comment]
cleaning old issues
